### ISSUE TITLE
[Bug] globalThis polyfill causes runtime errors in Safari

### ISSUE THREAD

**Issue by philbarresi** [MadProbe/iterator-helpers-polyfill#19]
**Describe the bug**
When the library is built and bundled, the globalThis polyfill will cause  errors to be throw in Safari due to the assignment of the global polyfill; turns into bad syntax somehow.

**To Reproduce**
1. Build an app for production (potenially using vite)
2. Navigate to the page in question. 
3. Open console. see error below.

**Expected behavior**
Expect Safari to load

**Screenshots** [Optional]
![Screen Shot 2023-09-03 at 12 06 40 AM](https://github.com/MadProbe/iterator-helpers-polyfill/assets/1325433/7ad61c7e-4d0a-4b7a-9e25-a4fbf03c7b67)

**Additional context**

Can see issue: https://prod.thinkalpha.io/

**Comment by MadProbe** [comment]
I don't have a mac to open safari and debug this, so I don't have enough information to do anything for now.

**Comment by MadProbe** [comment]
Ok, I have debugged this in remote safari browser session and seems like safari doesn't like non-ASCII characters in the names of variables that much :/. I'll deploy a fix with a different ASCII-only cryptic name for property soon.
Also I think this is a browser bug, so you could file a bug report at https://webcompat.com/issues/new with this.

**Comment by philbarresi** [comment]
Works fine now, thanks so much!
