### ISSUE TITLE
[Bug] null causes unique to blow up

### ISSUE THREAD

**Issue by bytenik** [MadProbe/iterator-helpers-polyfill#20]
**Describe the bug**
When a null is included in the iterated data, a `unique` helper will get an error.

**To Reproduce**
```
import { installIntoGlobal } from "iterator-helpers-polyfill"

installIntoGlobal()

{
  const it = [1, 2, 3, 4, 2, 4][Symbol.iterator]();
  const out = it.unique();
  console.log([...out])
}
{
  const it = [1, 2, 3, null][Symbol.iterator]();
  const out = it.unique();
  console.log([...out])
}
```

https://codesandbox.io/p/sandbox/amazing-frog-5cvzcs?file=%2Fsrc%2Fmain.tsx%3A1%2C1-14%2C2

**Comment by MadProbe** [comment]
Hmm, this is a quick fix and I just need to get to my computer to patch this as I haven't accounted for null when I have written semi weak map for `.unique()` values set.

**Comment by MadProbe** [comment]
Thank you for opening this issue, this should be fixed now in the new version

**Comment by bytenik** [comment]
Fantastic, thank you!
