### ISSUE TITLE
[Bug] counter/index argument is not provided to callback functions

### ISSUE THREAD

**Issue by julienroyer** [MadProbe/iterator-helpers-polyfill#22]
**Describe the bug**

For sync map/filter at least, only one argument is provided to the callback function (the current element).

[The iterator helpers proposal](https://tc39.es/proposal-iterator-helpers/#sec-iteratorprototype.map) specifies that the callback functions are provided two arguments: the current element and its counter/index.

**To Reproduce**

[...Iterator.from([0, 1]).filter((x, idx) => idx)]

**Expected behavior**

expected [1], got []

**Comment by MadProbe** [comment]
This has been fixed in version 3.0.0, and thank you for reporting this bug!
I still have in backlog making this polyfill more spec-compliant, and I have to carve out some time and will to make it as good as it can be.

**Comment by julienroyer** [comment]
Thanks a lot for fixing this bug!
