### ISSUE TITLE
This is neat, is this on npm? 

### ISSUE THREAD

**Issue by benjamingr** [MadProbe/iterator-helpers-polyfill#5]
I want to try it out :)

**Comment by MadProbe** [comment]
I will publish this module onto npm, except me to upload it in like 3-4 hours

**Comment by MadProbe** [comment]
Although this module needs to be documented, and this i will try to do in some time later as i am working on my other project.

**Comment by benjamingr** [comment]
@MadProbe ok, we're implementing all of this in Node core by the way, e.g. https://nodejs.org/api/stream.html#readablemapfn-options

**Comment by benjamingr** [comment]
Also thanks (for publishing this and making this!), to be clear I am just making a request, you owe me nothing, if this takes more time because you're working on something else take your time :]

**Comment by MadProbe** [comment]
OK, i've published a more polished version (2.1.0) onto NPM, feel free to play around with it @benjamingr!

**Comment by MadProbe** [comment]
Also i want to leave a note: to install polyfill into globalThis, you need to call `installIntoGlobal` function first.
But also you can import AsyncIterator and Iterator constructors directly.
Sorry - no documentation yet. :/

**Comment by benjamingr** [comment]
@MadProbe what's the package name? :)

**Comment by MadProbe** [comment]
same as the repository named: "iterator-helpers-polyfill"
